# aList = []
# print(aList.__sizeof__())
#
# # list contains the references of objects that are created instead of actual values that is why they are called
# containers of objects,they store multiple # object references in a single variable which are accessible with
# indexes. # 40(initial size of empty list)+8+8+8+8 = 72 aList.append(10) print(aList.__sizeof__())
#
# aList.append(20)
# print(aList.__sizeof__())
#
# aList.append(30)
# print(aList.__sizeof__())
#
# aList.append(40)
# print(aList.__sizeof__())
# print(aList)
#
# # when we add below element of 8 bytes to a new index in list along with it 3 more new reserve spaces will be
# created of 24 bytes. # going forward when list gets exhausted a new element will be added and new set of 24 will be
# opened up aList.append(50) print(aList.__sizeof__()) print(aList)
#
# aList.append(60)
# print(aList.__sizeof__())
#
# aList.append(70)
# print(aList.__sizeof__())
#
# aList.append(80)
# print(aList.__sizeof__())
#
# # it increased to 64 bytes, what is the formulae on which reserve space is allocated in list?
# aList.append(90)
# print(aList.__sizeof__())


print("---------------")

# indent shortcuts command + a and then ctrl+option+i


"""
How do lists works internally
"""

aList = []
print(aList.__sizeof__())
print("-----------------------------------")
aList.append("foo")
print(aList)
print(aList.__sizeof__())
# 40 + 8 + 8 + 8 + 8 = 72
print("-----------------------------------")
aList.insert(1, [1, 2, 3])
print(aList)
print(aList.__sizeof__())
print("-----------------------------------")
aList.append(10)
print(aList)
print(aList.__sizeof__())
print("-----------------------------------")
aList.append(10)
print(aList)
print(aList.__sizeof__())
print("-----------------------------------")
aList.append(10)
print(aList)
print(aList.__sizeof__())
print("-----------------------------------")

# Empty List
print("------------------------------------------ set 0")
aList = []
current_size = aList.__sizeof__()
print(current_size)

print("------------------------------------------ set 1")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
previous_total_size = aList.__sizeof__()
current_size = aList.__sizeof__() - current_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))

print("------------------------------------------ set 2")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))

print("previous_total_size", previous_total_size)
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 3")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 4")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 5")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 6")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 7")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 8")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 9")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 10")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 11")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 12")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 13")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 14")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 15")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 16")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
print("------------------------------------------ set 17")
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
aList.append(10)
print("Total size:" + str(aList.__sizeof__()))
current_size = aList.__sizeof__() - previous_total_size
print("Set size:" + str(current_size))
print("Total current set elements:" + str(current_size / 8))
previous_total_size = aList.__sizeof__()
